# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GeniusReferrals

  class Configuration
    # The base Uri for API calls
    @base_uri = 'https://api.geniusreferrals.com'

    # The content type
    @content_type = 'application/json'

    # Your API Token, you can get your token here https://www.geniusreferrals.com/en/settings/api-access
    @x_auth_token = '3b9d11374b602fb47b987dff90f1c5940a1f377f'

    # The attribute accessors for public properties
    class << self
      attr_accessor :base_uri
      attr_accessor :content_type
      attr_accessor :x_auth_token
    end
 
  end
end
