# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
require 'date'
require 'json'
require 'faraday'
require 'certifi'
require 'logging'

require_relative 'genius_referrals/api_helper.rb'
require_relative 'genius_referrals/genius_referrals_client.rb'

# Http
require_relative 'genius_referrals/http/http_call_back.rb'
require_relative 'genius_referrals/http/http_client.rb'
require_relative 'genius_referrals/http/http_method_enum.rb'
require_relative 'genius_referrals/http/http_request.rb'
require_relative 'genius_referrals/http/http_response.rb'
require_relative 'genius_referrals/http/http_context.rb'
require_relative 'genius_referrals/http/faraday_client.rb'
require_relative 'genius_referrals/http/auth/custom_header_auth.rb'

# Models
require_relative 'genius_referrals/models/base_model.rb'
require_relative 'genius_referrals/models/advocate.rb'
require_relative 'genius_referrals/models/advocate_form.rb'
require_relative 'genius_referrals/models/advocate_patch_form.rb'
require_relative 'genius_referrals/models/bonuses.rb'
require_relative 'genius_referrals/models/bonuses_form.rb'
require_relative 'genius_referrals/models/bonuses_1.rb'
require_relative 'genius_referrals/models/bonuses_form_1.rb'
require_relative 'genius_referrals/models/redemption_request.rb'
require_relative 'genius_referrals/models/redemption_request_form.rb'
require_relative 'genius_referrals/models/referral.rb'
require_relative 'genius_referrals/models/referral_form.rb'

# Exceptions
require_relative 'genius_referrals/exceptions/api_exception.rb'

require_relative 'genius_referrals/configuration.rb'

# Controllers
require_relative 'genius_referrals/controllers/base_controller.rb'
require_relative 'genius_referrals/controllers/roots_controller.rb'
require_relative 'genius_referrals/controllers/authentications_controller.rb'
require_relative 'genius_referrals/controllers/advocates_controller.rb'
require_relative 'genius_referrals/controllers/accounts_controller.rb'
require_relative 'genius_referrals/controllers/reports_controller.rb'
require_relative 'genius_referrals/controllers/referrals_controller.rb'
require_relative 'genius_referrals/controllers/redemption_requests_controller.rb'
require_relative 'genius_referrals/controllers/bonuses_controller.rb'
require_relative 'genius_referrals/controllers/campaigns_controller.rb'
