# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GeniusReferrals
  class ForceBonuses < BaseModel
    # The referral's token.
    # @return [String]
    attr_accessor :advocate_token

    # The reference number for this request. Usually the order_id, payment_id, or timestamp.
    # @return [String]
    attr_accessor :reference

    # The bonus amount to give to the advocate.
    # @return [Integer]
    attr_accessor :bonus_amount

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["advocate_token"] = "advocate_token"
        @hash["reference"] = "reference"
        @hash["bonus_amount"] = "bonus_amount"
      end
      @hash
    end

    def initialize(advocate_token = nil,
                   reference = nil,
                   bonus_amount = nil)
      @advocate_token = advocate_token
      @reference = reference
      @bonus_amount = bonus_amount
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        advocate_token = hash["advocate_token"]
        reference = hash["reference"]
        bonus_amount = hash["bonus_amount"]

        # Create object from extracted values
        ForceBonuses.new(advocate_token,
                         reference,
                         bonus_amount)
      end
    end
  end
end
