# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GeniusReferrals
  class PaymentMethodForm < BaseModel
    # The payment methods wrapper
    # @return [PaymentMethod]
    attr_accessor :advocate_payment_method

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["advocate_payment_method"] = "advocate_payment_method"
      end
      @hash
    end

    def initialize(advocate_payment_method = nil)
      @advocate_payment_method = advocate_payment_method
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        advocate_payment_method = PaymentMethod.from_hash(hash["advocate_payment_method"]) if hash["advocate_payment_method"]

        # Create object from extracted values
        PaymentMethodForm.new(advocate_payment_method)
      end
    end
  end
end
