# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GeniusReferrals
  class RedemptionRequestForm < BaseModel
    # The redemption request's wrapper
    # @return [RedemptionRequest]
    attr_accessor :redemption_request

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["redemption_request"] = "redemption_request"
      end
      @hash
    end

    def initialize(redemption_request = nil)
      @redemption_request = redemption_request
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        redemption_request = RedemptionRequest.from_hash(hash["redemption_request"]) if hash["redemption_request"]

        # Create object from extracted values
        RedemptionRequestForm.new(redemption_request)
      end
    end
  end
end
