# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GeniusReferrals
  class RedemptionRequest < BaseModel
    # The advocate's token
    # @return [String]
    attr_accessor :advocate_token

    # The request status identifier
    # @return [String]
    attr_accessor :request_status_slug

    # The request action identifier
    # @return [String]
    attr_accessor :request_action_slug

    # The currency code
    # @return [String]
    attr_accessor :currency_code

    # The amount to be redeemed
    # @return [Integer]
    attr_accessor :amount

    # The description of the requests, useful to store extra information about the request.
    # @return [String]
    attr_accessor :description

    # The advocate's PayPal username
    # @return [String]
    attr_accessor :advocates_paypal_username

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["advocate_token"] = "advocate_token"
        @hash["request_status_slug"] = "request_status_slug"
        @hash["request_action_slug"] = "request_action_slug"
        @hash["currency_code"] = "currency_code"
        @hash["amount"] = "amount"
        @hash["description"] = "description"
        @hash["advocates_paypal_username"] = "advocates_paypal_username"
      end
      @hash
    end

    def initialize(advocate_token = nil,
                   request_status_slug = nil,
                   request_action_slug = nil,
                   currency_code = nil,
                   amount = nil,
                   description = nil,
                   advocates_paypal_username = nil)
      @advocate_token = advocate_token
      @request_status_slug = request_status_slug
      @request_action_slug = request_action_slug
      @currency_code = currency_code
      @amount = amount
      @description = description
      @advocates_paypal_username = advocates_paypal_username
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        advocate_token = hash["advocate_token"]
        request_status_slug = hash["request_status_slug"]
        request_action_slug = hash["request_action_slug"]
        currency_code = hash["currency_code"]
        amount = hash["amount"]
        description = hash["description"]
        advocates_paypal_username = hash["advocates_paypal_username"]

        # Create object from extracted values
        RedemptionRequest.new(advocate_token,
                              request_status_slug,
                              request_action_slug,
                              currency_code,
                              amount,
                              description,
                              advocates_paypal_username)
      end
    end
  end
end
