# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GeniusReferrals
  class ReferralForm < BaseModel
    # The referral's wrapper
    # @return [Referral]
    attr_accessor :referral

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["referral"] = "referral"
      end
      @hash
    end

    def initialize(referral = nil)
      @referral = referral
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        referral = Referral.from_hash(hash["referral"]) if hash["referral"]

        # Create object from extracted values
        ReferralForm.new(referral)
      end
    end
  end
end
