# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GeniusReferrals
  class AuthenticationsController < BaseController
    @@instance = AuthenticationsController.new
    # Singleton instance of the controller class
    def self.instance
      @@instance
    end

    # Allow clients to test authentication on Genius Referrals platform.
    # @return Mixed response from the API call
    def get_authentication

      # prepare query url
      _query_builder = Configuration.base_uri.dup
      _query_builder << '/test-authentication'
      _query_url = APIHelper.clean_url _query_builder

      # prepare headers
      _headers = {
        'accept' => 'application/json',
        'Content-Type' => Configuration.content_type
      }

      # prepare and execute HttpRequest
      _request = @http_client.get _query_url, headers: _headers
      CustomHeaderAuth.apply(_request)
      _context = execute_request(_request)
      validate_response(_context)

      # return appropriate response type
      decoded = APIHelper.json_deserialize(_context.response.raw_body) if not (_context.response.raw_body.nil? or _context.response.raw_body.to_s.strip.empty?)
      return decoded
    end
  end
end
